[project]
name = "kiara-project-viewer"
version = "0.1.0"
description = "kiara project viewer"
authors = []
channels = ["dharpa", "conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
show-versions = "kiara --version"
delete-context = "kiara context delete"
streamlit = "streamlit run"
kiara = "kiara"


[dependencies]
"kiara_plugin.onboarding" = ">=0.5.0,<0.6.0"
kiara = ">=0.5.3"
"kiara_plugin.tabular" = ">=0.5.0,<0.6.0"
python = ">=3.11.0,<3.12.0"
"kiara_plugin.language_processing" = ">=0.5.0,<0.6.0"
"kiara_plugin.network_analysis" = ">=0.5.0,<0.6.0"
"kiara_plugin.streamlit" = ">=0.5.0,<0.6.0"
"kiara_plugin.html" = ">=0.5.0,<0.6.0"
